Repository ucsb-cs156-w24/proj-organic-w24-6pm-2, pull requests merged in 2024-03, with the labels that each got.

#17 Instructor can create, edit, delete a course
  src/main/java/edu/ucsb/cs156/organic/controllers/CoursesController.java
  src/test/java/edu/ucsb/cs156/organic/controllers/CoursesControllerTests.java
Labels: 10

#30 KL - FEATURE: [Frontend] Normal User Join Action
  frontend/src/main/components/Courses/CoursesTable.js
  frontend/src/tests/components/Courses/CoursesTable.test.js
Labels: 5

#31 Demir pop up when toggle
  frontend/package-lock.json
  frontend/package.json
  frontend/src/main/components/Users/UsersTable.js
  frontend/src/tests/pages/AdminUsersPage.test.js
Labels: 10

#33 Vincent organic last online bug
  frontend/src/main/components/Users/UsersTable.js
  frontend/src/main/utils/dateUtils.js
  frontend/src/tests/utils/dateUtils.test.js
Labels: 5

#35 COMPLETED Fixed Course Dates Bug
  frontend/src/main/components/Courses/CoursesForm.js
  frontend/src/tests/components/Courses/CoursesForm.test.js
  frontend/src/tests/pages/CoursesEditPage.test.js
  src/main/java/edu/ucsb/cs156/organic/controllers/CoursesController.java
  src/test/java/edu/ucsb/cs156/organic/controllers/CoursesControllerTests.java
Labels: 5

#44 COMPLETED PR for Epic-School-and-Term-validations-F2
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/School/SchoolTable.js
  frontend/src/main/components/Utils/SchoolUtils.js
  frontend/src/main/pages/SchoolCreatePage.js
  frontend/src/main/pages/SchoolEditPage.js
  frontend/src/main/pages/SchoolIndexPage.js
  frontend/src/stories/components/School/SchoolTable.stories.js
  frontend/src/stories/pages/SchoolCreatePage.stories.js
  frontend/src/stories/pages/SchoolEditPage.stories.js
  frontend/src/stories/pages/SchoolIndexPage.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/components/School/SchoolTable.test.js
  frontend/src/tests/components/Utils/SchoolUtils.test.js
  frontend/src/tests/pages/SchoolCreatePage.test.js
  frontend/src/tests/pages/SchoolEditPage.test.js
  frontend/src/tests/pages/SchoolIndexPage.test.js
  src/main/java/edu/ucsb/cs156/organic/Interceptors/RoleUserInterceptor.java
  src/main/java/edu/ucsb/cs156/organic/Interceptors/RoleUserInterceptorAppConfig.java
  src/test/java/edu/ucsb/cs156/organic/Interceptors/RoleUserInterceptorTests.java
Labels: 15

#42 COMPLETED Implementing School Entity/Repository Classes and Migration File
  src/main/java/edu/ucsb/cs156/organic/entities/School.java
  src/main/java/edu/ucsb/cs156/organic/repositories/SchoolRepository.java
  src/main/resources/db/migration/changes/0007_CreateSchoolTable.json
Labels: 10
